<?php

namespace AppUnitTests;

use App\Calculator;
use PHPUnit\Framework\TestCase;

// php7.4 vendor/phpunit/phpunit/phpunit ./tests
class CalculatorTest extends TestCase
{
    /**
     * @var Calculator
     */
    private $calculator;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->calculator = new Calculator();
    }

    public function testAdd(): void
    {
        $result =$this->calculator->add(2,3);

        self::assertEquals(5, $result);
    }
}